# global settings
title: "Repo Reviews"
description: "Support the community with a helpful ❤️ repo review ❤️"
permalink: "/:title"
url: https://repo-reviews.github.io
relative_permalinks: false

# build settings
exclude: ["script", "docs", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules", "create.md", "new_reviews"]
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons

theme: minima

# sass:
#  style: :compressed
#  # Where you keep your scss files
#  sass_dir: assets/css/
#  # Where sass should look for other scss
#  load_paths:
#    - node_modules/

collections:
  reviews:
    output: true
  authors:
    output: true
  repos:
    output: true


